<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '--Select--' => 'выбрать',
    'Category' => 'категория',
    'Category ID' => 'категория',
    'Choose category' => 'выберите категорию',
    'Choose region' => 'выберите регион',
    'Create' => 'создать',
    'Created at' => 'создано в',
    'Email' => 'електронная почта',
    'ID' => 'ID',
    'Local' => 'язык',
    'Person' => 'ФИО',
    'Phone' => 'телефонный номер',
    'Region' => 'регион',
    'Region ID' => 'регион',
    'Select publication date' => 'выберите дату публикации',
    'Site' => 'сайт',
    'Status' => 'статус',
    'Text' => 'текст',
    'Title' => 'заголовок',
    'Update' => 'обновить',
    'announcement' => 'обьявление',
    'announcements' => 'обьявления',
];
